"""Syncthing integration: configuration discovery, folder resolution, activity
monitoring, and watch management."""

from __future__ import annotations

from ._types import (
    EVENT_TYPES,
    DEFAULT_API_URL,
    DEFAULT_ACTIVE_WINDOW_SECONDS,
    DEFAULT_POLL_INTERVAL_SECONDS,
    DEFAULT_EVENT_TIMEOUT_SECONDS,
    DEFAULT_STATUS_POLL_INTERVAL_SECONDS,
    DEFAULT_MIN_RATE_BYTES_PER_SECOND,
    COMMON_SYNCTHING_FLATPAK_IDS,
    PREPARING_STATES,
    SCANNING_STATES,
    ERROR_STATES,
    PAUSED_STATES,
    SyncthingConfig,
    FolderSelection,
    FolderRuntime,
    RemoteProgress,
    ConnectionRates,
    LocalActivity,
    ActivityStatus,
    normalize_path,
    is_inside,
    bool_from_xml_attr,
    int_field,
    parse_folder_runtime,
)
from .api import SyncthingAPI
from .config import (
    SyncthingNotConfiguredError,
    api_url_from_gui_address,
    candidate_config_files,
    discover_syncthing_config,
    parse_syncthing_config,
    resolve_api_credentials,
)
from .folders import (
    get_folders,
    folder_label,
    folder_selection_from_config,
    resolve_folder_by_id,
    resolve_folder_by_path,
)
from .activity import (
    get_folder_status,
    get_initial_folder_state_and_runtime,
    get_event_cursor,
    get_events,
    get_connection_totals,
    compute_rates,
    prune_remote_progress,
    prune_local_activity,
    compute_activity_status,
    process_event,
)
from .watcher import SyncthingWatch, SyncthingWatchManager

__all__ = [
    "EVENT_TYPES",
    "DEFAULT_API_URL",
    "DEFAULT_ACTIVE_WINDOW_SECONDS",
    "DEFAULT_POLL_INTERVAL_SECONDS",
    "DEFAULT_EVENT_TIMEOUT_SECONDS",
    "DEFAULT_STATUS_POLL_INTERVAL_SECONDS",
    "DEFAULT_MIN_RATE_BYTES_PER_SECOND",
    "COMMON_SYNCTHING_FLATPAK_IDS",
    "PREPARING_STATES",
    "SCANNING_STATES",
    "ERROR_STATES",
    "PAUSED_STATES",
    "SyncthingConfig",
    "FolderSelection",
    "FolderRuntime",
    "RemoteProgress",
    "ConnectionRates",
    "LocalActivity",
    "ActivityStatus",
    "normalize_path",
    "is_inside",
    "bool_from_xml_attr",
    "int_field",
    "parse_folder_runtime",
    "SyncthingAPI",
    "SyncthingNotConfiguredError",
    "api_url_from_gui_address",
    "candidate_config_files",
    "discover_syncthing_config",
    "parse_syncthing_config",
    "resolve_api_credentials",
    "get_folders",
    "folder_label",
    "folder_selection_from_config",
    "resolve_folder_by_id",
    "resolve_folder_by_path",
    "get_folder_status",
    "get_initial_folder_state_and_runtime",
    "get_event_cursor",
    "get_events",
    "get_connection_totals",
    "compute_rates",
    "prune_remote_progress",
    "prune_local_activity",
    "compute_activity_status",
    "process_event",
    "SyncthingWatch",
    "SyncthingWatchManager",
]
